/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package vista;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.IOException;
import java.net.URISyntaxException;


public class FrmEva extends javax.swing.JDialog {

    /**
     * Creates new form FrmEva
     */
    public FrmEva(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        initEventHandlers();
          pack();
        setLocationRelativeTo(null);
    }
 private void initEventHandlers() {
        // Agrega ActionListener a los botones
        btnRecursos.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                // Cambia al panel de Recursos cuando se hace clic en btnRecursos
                panel.setSelectedIndex(0); // El índice 0 representa el primer panel (Recursos)
            }
        });

        btnTareas.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                // Cambia al panel de Tareas cuando se hace clic en btnTareas
                panel.setSelectedIndex(1); // El índice 1 representa el segundo panel (Tareas)
            }
        });
         btnZoom.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                // Cambia al panel de Tareas cuando se hace clic en btnTareas
                panel.setSelectedIndex(2); // El índice 1 representa el segundo panel (Tareas)
            }
        });
    }
 
 private void abrirZoom(){
     if(java.awt.Desktop.isDesktopSupported()){
         java.awt.Desktop desktop=java.awt.Desktop.getDesktop();
         
         if(desktop.isSupported(java.awt.Desktop.Action.BROWSE)){
             try{
                 java.net.URI uri=new java.net.URI("https://us04web.zoom.us/j/73780831526?pwd=7fwx2RZG3FdxOOTmapolsa8WzEqhXm.1");
                 desktop.browse(uri);
             }catch(URISyntaxException | IOException ex) {
                 
             }
         }
     }
 }
 
  private void abrirYoutube(){
     if(java.awt.Desktop.isDesktopSupported()){
         java.awt.Desktop desktop=java.awt.Desktop.getDesktop();
         
         if(desktop.isSupported(java.awt.Desktop.Action.BROWSE)){
             try{
                 java.net.URI uri=new java.net.URI("https://www.youtube.com/channel/UCZwQEWob-TMxY7vUQTkhLsQ");
                 desktop.browse(uri);
             }catch(URISyntaxException | IOException ex) {
                 
             }
         }
     }
 }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnTareas = new javax.swing.JButton();
        btnRecursos = new javax.swing.JButton();
        panel = new javax.swing.JTabbedPane();
        panelRecursos = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        panelTareas = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        btnZoom = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Eva");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnTareas.setText("Tutorias");
        jPanel1.add(btnTareas, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, -1));

        btnRecursos.setText("Recurso Didacticos");
        jPanel1.add(btnRecursos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        panel.setEnabled(false);

        panelRecursos.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setText("Videos Tutoriales");

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/img/youtube.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelRecursosLayout = new javax.swing.GroupLayout(panelRecursos);
        panelRecursos.setLayout(panelRecursosLayout);
        panelRecursosLayout.setHorizontalGroup(
            panelRecursosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRecursosLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addContainerGap(1324, Short.MAX_VALUE))
        );
        panelRecursosLayout.setVerticalGroup(
            panelRecursosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRecursosLayout.createSequentialGroup()
                .addGroup(panelRecursosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRecursosLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel2))
                    .addGroup(panelRecursosLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jButton2)))
                .addContainerGap(768, Short.MAX_VALUE))
        );

        panel.addTab("Recursos", panelRecursos);

        panelTareas.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setText("Tareas");

        javax.swing.GroupLayout panelTareasLayout = new javax.swing.GroupLayout(panelTareas);
        panelTareas.setLayout(panelTareasLayout);
        panelTareasLayout.setHorizontalGroup(
            panelTareasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTareasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(1441, Short.MAX_VALUE))
        );
        panelTareasLayout.setVerticalGroup(
            panelTareasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTareasLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel3)
                .addContainerGap(769, Short.MAX_VALUE))
        );

        panel.addTab("Tareas", panelTareas);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setText("Enlace de reunion");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/img/zoom.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(1315, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(189, 189, 189)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel4))
                    .addComponent(jButton1))
                .addContainerGap(610, Short.MAX_VALUE))
        );

        panel.addTab("Zoom", jPanel2);

        jPanel1.add(panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(196, 18, 1480, 860));

        btnZoom.setText("Zoom");
        jPanel1.add(btnZoom, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/img/logoEsquina.png"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        abrirZoom();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        abrirYoutube();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(FrmEva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(FrmEva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(FrmEva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(FrmEva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                FrmEva dialog = new FrmEva(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRecursos;
    private javax.swing.JButton btnTareas;
    private javax.swing.JButton btnZoom;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTabbedPane panel;
    private javax.swing.JPanel panelRecursos;
    private javax.swing.JPanel panelTareas;
    // End of variables declaration//GEN-END:variables
}
