/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.Administracion;

import controlador.ControlarMatricula;
import javax.swing.JOptionPane;
import modelo.Matricula;
import modelo.tabla.ModeloTablaEstudiante;
import modelo.tabla.ModeloTablaMatricula;
import vista.utilidades.Utilidades;

/**
 *
 * @author cristian
 */
public class pnlAsignar extends javax.swing.JPanel {

    private ModeloTablaMatricula modelo = new ModeloTablaMatricula();
    private ControlarMatricula control = new ControlarMatricula();
     private ModeloTablaEstudiante modeloE = new ModeloTablaEstudiante();

    /**
     * Creates new form pnlHome
     */
    public pnlAsignar() {
        initComponents();
        
    }

  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 671, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 517, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
